# @package _global_

defaults:
  - h1
dataset:
  scale_ratio: 1.0
  falcon_h1:
    respect_trial_boundaries: False
    chop_size_ms: 2000
  augmentations: ['explicit_crop_time']
train:
  max_batch_size: 32
  batch_size: 32
sweep_cfg: chop_coarse_2s