# @package _global_

defaults:
  - /model: flat_enc_dec
  - /model/task:
    - joint_bhvr_decode_flat
  - /dataset: flat
model:
  causal: true
  neurons_per_token: 32
  session_embed_strategy: EmbedStrat.token
  transformer:
    max_trial_length: 200 # 2 seconds
    n_layers: 6
  task:
    mask_ratio: 0.25 # for efficiency
    task_weights: [1.0, 1.0]
    decode_time_pool: ''
    decode_normalizer: './data/zscore_h1_7d.pt'
  dropout: 0.1
dataset:
  bin_size_ms: 20
  max_length_ms: 4000
  max_tokens: 8192 # expecting 6 tokens/bin x 500 bins = 3000 tokens

  neurons_per_token: 32
  max_channels: 192
  max_arrays: 1

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  - DataKey.bhvr_mask
  datasets:
  - falcon_FALCONH1.*
  behavior_dim: 7

train:
  max_batch_size: 32
  batch_size: 32
  patience: 300

sweep_cfg: 'h1_fine_grained_discrete'
sweep_mode: 'grid'