# @package _global_
defaults:
  - /model:
    - flat_enc_dec
  - /model/task:
    - joint_bhvr_decode_flat
  - /dataset: flat
model:
  session_embed_token_count: 8
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 16

  causal: True
  task:
    mask_ratio: 0.5
    task_weights: [1.0, 1.0]
    behavior_lag: 0
    decode_time_pool: "mean"
    decode_normalizer: pitt_obs_zscore.pt

dataset:
  max_tokens: 8192
  max_length_ms: 2000 # fit
  max_arrays: 2

  neurons_per_token: 16
  max_channels: 192

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  datasets:
  - P2Home.data.00329
  - P2Home.data.00336
  - P2Home.data.00339
  - P2Home.data.00345
  - P2Home.data.00360
  - P2Home.data.00371
  - P2Home.data.00402
  - P2Home.data.00422
  - P2Home.data.00424
  - P2Home.data.00437
  - P2Home.data.00445

  eval_datasets:
  - P2Home.data.00445
  # - observation_P2Lab_session_1926.*

train:
  autoscale_batch_size: false
  batch_size: 32
init_from_id: bci_pt_causal-21wye93c
init_tag: val_loss