# @package _global_

tag: factor_pitt_obs_causal

defaults:
  - /model: pretrain_2x
  - /train: pretrain
dataset:
  datasets:
  - P2Home.data.00329
  - P2Home.data.00336
  - P2Home.data.00339
  - P2Home.data.00345
  - P2Home.data.00360
  - P2Home.data.00371
  - P2Home.data.00402
  - P2Home.data.00422
  - P2Home.data.00424
  - P2Home.data.00437
  # Holdout for decoding eval
  # - P2Home.data.00445
  eval_datasets:
  - P2Home.data.00437
  pitt_co:
    arrays:
    - P2-lateral_m1
    - P2-medial_m1
  max_length_ms: 4000
  max_arrays: 2
  bin_size_ms: 20
  max_channels: 96
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
model:
  task:
    tasks:
    - ModelTask.next_step_prediction
    metrics:
    - Metric.bps
  spike_embed_style: EmbedStrat.token
  neurons_per_token: 1 # 4 is slightly worse, 16 is even worse
  hidden_size: 256
  transform_space: true
  transformer:
    factorized_space_time: true
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.none