# @package _global_

tag: pitt_single

defaults:
  - /model: pretrain_small
  - /train: nlb
dataset:
  datasets:
  - P2Home.data.00329
  data_keys:
  - DataKey.spikes
  pitt_co:
    arrays:
    - P2-lateral_m1
    - P2-medial_m1
    - P2-sensory
  max_length_ms: 4000
  max_arrays: 3
  bin_size_ms: 5
  max_channels: 96
model:
  dropout: 0.8
  transformer:
    dropout: 0.8
    n_heads: 2
    n_layers: 4
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
train:
  patience: 6000
  batch_size: 16