# @package _global_

tag: pitt_obs_20

defaults:
  - /model: pretrain
  - /train: nlb
dataset:
  datasets:
  - P2Home.data.00329
  - P2Home.data.00336
  - P2Home.data.00339
  - P2Home.data.00345
  - P2Home.data.00360
  - P2Home.data.00371
  - P2Home.data.00402
  - P2Home.data.00422
  - P2Home.data.00424
  - P2Home.data.00437
  - P2Home.data.00445
  eval_datasets:
  - P2Home.data.00445
  data_keys:
  - DataKey.spikes
  pitt_co:
    arrays:
    - P2-lateral_m1
    - P2-medial_m1
    - P2-sensory
  max_length_ms: 4000
  max_arrays: 3
  bin_size_ms: 20
  max_channels: 96
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
model:
  task:
    tasks:
    - ModelTask.infill
    metrics:
    - Metric.bps
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
# sweep_cfg: base