# @package _global_

defaults:
  - m1
dataset:
  scale_ratio: 1.0
train:
  max_batch_size: 128
  batch_size: 128
  autoscale_batch_size: false
  patience: 200

sweep_cfg: 'h1_fine_grained_discrete'
sweep_mode: 'grid'