# @package _global_

defaults:
  - m1
dataset:
  scale_ratio: 0.25
train:
  max_batch_size: 32
  batch_size: 32
  autoscale_batch_size: false
  patience: 200

sweep_cfg: 'h1_fine_grained_discrete'
sweep_mode: 'grid'