# @package _global_

tag: pitt_decode

defaults:
  - /model: pretrain
  - /train: nlb
dataset:
  datasets:
  - P2Home.data.00329
  - P2Home.data.00336
  - P2Home.data.00339
  - P2Home.data.00345
  - P2Home.data.00360
  - P2Home.data.00371
  - P2Home.data.00402
  - P2Home.data.00422
  - P2Home.data.00424
  - P2Home.data.00437
  - P2Home.data.00445
  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
  pitt_co:
    arrays:
    - P2-lateral_m1
    - P2-medial_m1
    - P2-sensory
  max_length_ms: 4000
  max_arrays: 3
  bin_size_ms: 20
  max_channels: 96
  behavior_dim: 2
  meta_keys:
  - MetaKey.unique
  - MetaKey.session
  - MetaKey.array
  - MetaKey.subject
model:
  dropout: 0.3
  transformer:
    dropout: 0.3
    n_heads: 2
    n_layers: 6
  task:
    tasks:
    - ModelTask.kinematic_decoding
    # - ModelTask.infill
    metrics: []
    # - Metric.bps
  subject_embed_strategy: EmbedStrat.token
  array_embed_strategy: EmbedStrat.token_add
train:
  batch_size: 16
  accumulate_batches: 4
init_from_id: pitt_20-tou7etu2