# @package _global_
defaults:
  - /model:
    - flat_enc_dec
  - /dataset: flat
model:
  session_embed_token_count: 1 # Keep it low for maybe easier FT?
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 32
  causal: True
  task:
    mask_ratio: 0.5
dataset:
  datasets:
  - observation_.*
  - ortho_.*
  - fbc_.*
  - unstructured_.*
  - pitt_co.*
  exclude_datasets:
  - closed_loop.*
  - observation_P2_19.* #
  - observation_P3_15.*
  - observation_P3_16.*
  # There are at least 4 test sessions for P3 and 8 for P2Lab
train:
  patience: 250
  autoscale_batch_size: false
  batch_size: 512
