# @package _global_
defaults:
  - _default
dataset:
  datasets:
  - observation_P2Lab_session_18.*
  - observation_P2Lab_session_19.*
  exclude_datasets:
  - observation_P2Lab_session_19.* #
  - observation_P3Lab_session_15.*
  - observation_P3Lab_session_16.*
  # There are at least 4 test sessions for P3 and 8 for P2Lab
train:
  autoscale_batch_size: false
  batch_size: 32
